export enum GenreEnum {
    PointAndClick = 2,
    Fighting = 4,
    Shooter = 5,
    Music = 7,
    Platform = 8,
    Puzzle = 9,
    Racing = 10,
    RealTimeStrategyRTS = 11,
    RolePlayingRPG = 12,
    Simulator = 13,
    Sport = 14,
    Strategy = 15,
    TurnBasedStrategyTBS = 16,
    Tactical = 24,
    HackAndSlash_BeatEmUp = 25,
    Quiz_Trivia = 26,
    Pinball = 30,
    Adventure = 31,
    Indie = 32,
    Arcade = 33,
    VisualNovel = 34,
    CardAndBoardGame = 35,
    MOBA = 36
}